### ISSUE TITLE
关于加入碧蓝幻想汉化项目的请求

### ISSUE THREAD

**Issue by damaozi** [BLHXFY-Group/BLHXFY#26]
项目发起者：
       您好，感谢您对中文玩家的无私帮助与支持。
       我作为一名骑空士，对您的发起的此汉化项目十分感兴趣，因此想要加入您的汉化项目，为碧蓝幻想的中文化推广尽一丝绵薄之力。我自认尚具备一定的翻译能力，还望您能够考虑我的请求。
       祝工作顺利。 
                        
                                                                                                                                    留恋榴莲牛奶

**Comment by biuuu** [comment]
https://github.com/BLHXFY-Group
邀请了，点这个链接可以接受。
