### ISSUE TITLE
您好，我想翻译主线哓之空88章以后的剧情

### ISSUE THREAD

**Issue by reizuki01** [BLHXFY-Group/BLHXFY#36]
您好，我想翻译主线哓之空88章以后的剧情
目前把剩下的88-3和88-4做好了，之后的文本已经准备好，着手起来做应该会很快
由于88章后有许多在统一章节内分了不同csv文件的情况，对于上传有一定的疑问
希望能得到帮助，谢谢！

**Comment by biuuu** [comment]
什么不同csv，什么样的

**Comment by reizuki01** [comment]
就是像发给您的这样，88章第四节分了两段文本




------------------ 原始邮件 ------------------
发件人: "biuuu"<notifications@github.com>; 
发送时间: 2019年6月29日(星期六) 上午10:49
收件人: "BLHXFY-Group/BLHXFY"<BLHXFY@noreply.github.com>; 
抄送: "rei"<rei01@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [BLHXFY-Group/BLHXFY] 您好，我想翻译主线哓之空88章以后的剧情 (#36)




什么不同csv，什么样的

**Comment by biuuu** [comment]
正常情况，可以参考之前的文件命名。
https://github.com/BLHXFY-Group/BLHXFY/tree/master/data/scenario/%E4%B8%BB%E7%BA%BF%E5%89%A7%E6%83%85/%E8%8B%8D%E4%B9%8B%E5%B0%91%E5%A5%B3

**Comment by reizuki01** [comment]
ok了解了，那我这边翻译好了就直接上传好啦？

**Comment by biuuu** [comment]
是的。
你好像下载的带机翻的剧情文本，里面会多一行机翻的备注文本，需要去掉。
然后我看到很多用单引号的地方，似乎应该直接用双引号。

**Comment by reizuki01** [comment]
原来这样，我这就去修改！
因为对代码知识约等于零，想着下载带机翻的话只要替换了中文就行。如果还发现有什么疏漏请务必告知，谢谢！




------------------ 原始邮件 ------------------
发件人: "biuuu"<notifications@github.com>; 
发送时间: 2019年6月29日(星期六) 中午11:04
收件人: "BLHXFY-Group/BLHXFY"<BLHXFY@noreply.github.com>; 
抄送: "rei"<rei01@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [BLHXFY-Group/BLHXFY] 您好，我想翻译主线哓之空88章以后的剧情 (#36)




是的。
 你好像下载的带机翻的剧情文本，里面会多一行机翻的备注文本，需要去掉。
 然后我看到很多用单引号的地方，似乎应该直接用双引号。

**Comment by biuuu** [comment]
你可以用预览看一遍，没什么问题的话，说明格式就是对的。

**Comment by reizuki01** [comment]
预览过后大概知道是个什么原理了，翻译还有需要改进的地方，等会要出门，就把已经上传的删掉了，明天修一遍再上传。顺便问一句上传后是没办法立马在游戏里看到的对嘛？




------------------ 原始邮件 ------------------
发件人: "biuuu"<notifications@github.com>; 
发送时间: 2019年6月29日(星期六) 中午11:44
收件人: "BLHXFY-Group/BLHXFY"<BLHXFY@noreply.github.com>; 
抄送: "rei"<rei01@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [BLHXFY-Group/BLHXFY] 您好，我想翻译主线哓之空88章以后的剧情 (#36)




你可以用预览看一遍，没什么问题的话，说明格式就是对的。

**Comment by biuuu** [comment]
需要我手动更新，一般一天之内能看到吧。

**Comment by reizuki01** [comment]
一直以来辛苦了！目前上传了88-3（跑过预览已经没太大问题了），剩下的部分从明天开始上传，今后请多关照！


 
---原始邮件---
发件人: "biuuu"<notifications@github.com>
发送时间: 2019年6月29日(星期六) 中午1:10
收件人: "BLHXFY-Group/BLHXFY"<BLHXFY@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"reizuki01"<rei01@qq.com>;
主题: Re: [BLHXFY-Group/BLHXFY] 您好，我想翻译主线哓之空88章以后的剧情 (#36)



需要我手动更新，一般一天之内能看到吧。
