### ISSUE TITLE
加入翻译

### ISSUE THREAD

**Issue by LesterZ819** [BLHXFY-Group/BLHXFY#41]
可以提供英文文本的翻译，润色等。

**Comment by biuuu** [comment]
英文翻译不会优先使用，所以要确认下是否跟其他人冲突。
加下QQ群吧 873667462

**Comment by LesterZ819** [comment]
您好，QQ群号查不到，可以看一下吗？ 发送自 Windows 10 版邮件应用 发件人: biuuu发送时间: Wednesday, January 1, 2020 11:36 PM收件人: BLHXFY-Group/BLHXFY抄送: LesterZ819; Author主题: Re: [BLHXFY-Group/BLHXFY] 加入翻译 (#41) 英文翻译不会优先使用，所以要确认下是否跟其他人冲突。加下QQ群吧 873667462—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by biuuu** [comment]
873667462 好了，可以搜到了
