### ISSUE TITLE
Git access request

### ISSUE THREAD

**Issue by MrPhoenix** [BLHXFY-Group/BLHXFY#43]
你好！我本人是一个玩了快一年的玩家，最近才开始使用汉化插件，感觉打开了新世界的大门。。赞美大佬！！
我本人不懂日语，但是英文还算比较流利，可以协助英翻。尤其是我发现英文人物名字已经很久没有更新过了，所以希望可以contribute。麻烦给我Git的权限，谢谢~

**Comment by MrPhoenix** [comment]
顺便想请问一下，似乎在语言设置为英文的时候不能Load人物技能和武器技能的汉化？请问这个是已知的问题吗？

**Comment by biuuu** [comment]
英文版的翻译基本放弃了，因为同时翻译两种语言会很麻烦。
现在主要只翻译日语版的内容。

**Comment by biuuu** [comment]
https://github.com/BLHXFY-Group
点链接加入group
