### ISSUE TITLE
提交翻译（SSR维恩终突剧情）

### ISSUE THREAD

**Issue by KusakaHaruka** [BLHXFY-Group/BLHXFY#46]
打扰了。
因为没有看到SSR维恩终突剧情翻译更新的样子，所以想来做一下翻译，目前80级前置剧情完成了3/4，今天内会上传全部4节并开始着手100级相关剧情。
又及：目前的SS有没有具体的翻译计划可以参考？想要翻译过去四骑士相关的活动剧情（以及包括马上开启的佣兵工作帖等等活动的剧情），但是不确定有没有其他翻译接手过这方面工作，有点不太好开工。

**Comment by biuuu** [comment]
873667462
可以加群看下占坑表
