### ISSUE TITLE
仇闪的技能描述有误

### ISSUE THREAD

**Issue by toadworshiper** [BLHXFY-Group/BLHXFY#49]
rt

**Comment by shala9999** [comment]
仇闪酱的话已修复

**Comment by biuuu** [comment]
https://github.com/BLHXFY-Group/BLHXFY/commit/f2840baf5df0051652e3605ce13c7750e735238b
还有问题吗

**Comment by toadworshiper** [comment]
> [f2840ba](https://github.com/BLHXFY-Group/BLHXFY/commit/f2840baf5df0051652e3605ce13c7750e735238b)
> 还有问题吗

还有就是怎么加这个组。。

**Comment by shala9999** [comment]
你先进群873667462
